#   _____                 ____  __.__                
#  /     \ _____  ___  __|    |/ _|__| ____    ____  
# /  \ /  \\__  \ \  \/  /      < |  |/    \  / ___\ 
#/    Y    \/ __ \_>    <|    |  \|  |   |  \/ /_/  >
#\____|__  (____  /__/\_ \____|__ \__|___|  /\___  / 
#        \/     \/      \/       \/       \//_____/  

#If you have any questions or problems, you can ask on the support server: https://discord.gg/Vr46JHm2kd
#Remember not to delete any line of code.
#For problems, bugs, ideas or suggestions you can do it on the discord server.
general:
  language: "en"
  #Check for updates on startup and periodically while the server is running?
  update-check: true
  #Send anonymous usage metrics to bStats?
  bstats: true
  prefix: "&#1621F5&lMaxEvo &8» "