name: MaxEvo
version: 1.0.0
main: org.zkaleejoo.MaxEvo
api-version: '1.21'
folia-supported: true
authors: [ ZkAleeJoo ]
description: Plugin to evolve your weapons

commands:
  maxevo:
    description: Main MaxEvo command
    aliases: [maxevo, me, evo]
    
permissions:
  maxevo.admin:
    description: Full access to MaxEvo and administrative commands.
    default: op
    children: []